import { ConversationService } from '../services/conversationService';
export class RetryFeedbackAgent {
  constructor(private conversationService: ConversationService) {}

  async recordFailure(
    errorType: 'validation' | 'compilation',
    conversationId: string,
    scadCode: string,
    format: 'stl' | '3mf',
    errorMessage: string,
    previewUrl?: string
  ): Promise<void> {
    switch (errorType) {
      case 'validation':
        await this.recordValidationFailure(conversationId, scadCode, format, errorMessage, previewUrl);
        break;
      case 'compilation':
        await this.recordCompilationFailure(conversationId, scadCode, format, errorMessage);
        break;
    }
  }

  async recordValidationFailure(
    conversationId: string,
    scadCode: string,
    format: 'stl' | '3mf',
    errorMessage: string,
    previewUrl?: string
  ): Promise<void> {
    await this.conversationService.addAssistantMessage(
      conversationId,
      `The model generated by OpenSCAD does not meet that user's request. Error: ${errorMessage}.`,
      '', // dont add scad bc it is in a previous message
      undefined,
      format,
      previewUrl
    );
  }

  async recordCompilationFailure(
    conversationId: string,
    scadCode: string,
    format: 'stl' | '3mf',
    errorMessage: string
  ): Promise<void> {
    await this.conversationService.addAssistantMessage(
      conversationId,
      'Generated OpenSCAD code (failed to compile).',
      '', // dont add scad bc it is in a previous message
      undefined,
      format
    );

    await this.conversationService.addUserMessage(
      conversationId,
      `The previous OpenSCAD code failed to compile. Error: ${errorMessage}. Please fix the code and return the complete updated OpenSCAD source.`
    );
  }
}
